### ISSUE TITLE
TODO: Ditch React, migrate to Vanilla Typescript

### ISSUE THREAD

**Issue by DuskyElf** [DuskyElf/elfmsg#27]
# Implement from #15 - except use Vanilla Typescript, also transfer to axum from rocket.rs

- [x] Update frontend to use vanilla Typescript
- [x] Update backend to Axum
- [x] Change README.md
